name: ubenwa_nkechi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.3
  hooks_riverpod: ^2.4.3
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  smooth_page_indicator: ^1.1.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  background_image: "assets/images/splash.png"
  image: "assets/images/logo.png"
  ios: true
  android: true

android_12:
  image: "assets/images/logo.png"
  background_image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
