name: ubenwa_nkechi
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.3.3
  flutter_svg: ^2.0.7
  go_router: ^10.0.0
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.1.0
  fl_chart: ^0.64.0
  hooks_riverpod: ^2.4.3
  cupertino_icons: ^1.0.2
  percent_indicator: ^4.2.3
  intl: ">=0.17.0 <0.19.0"
  scrollable_positioned_list: ^0.3.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1

flutter_native_splash:
  background_image: "assets/images/splash.png"
  image: "assets/images/logo.png"
  ios: true
  android: true

android_12:
  image: "assets/images/logo.png"
  background_image: "assets/images/splash.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
